name: Tests

on:
  push:
    # This should disable running the workflow on tags, according to the
    # on.<push|pull_request>.<branches|tags> GitHub Actions docs.
    branches:
      - "*"
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs.
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test-py310:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crdb-version: ["latest-v22.2"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install system packages for Django's Python test dependencies
        run: |
          sudo apt-get update
          sudo apt-get install binutils gdal-bin
      - name: Start CockroachDB
        run: |
          docker pull cockroachdb/cockroach:${{ matrix.crdb-version }}
          docker run --rm -d --name crdb -p 26257:26257 \
            cockroachdb/cockroach:${{ matrix.crdb-version }} start-single-node --insecure
      - name: Test
        run: bash teamcity-build/build-teamcity.sh
